// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB126k7DsM6OJVSp2L_TV-0bo-tFTR3rjI',
    appId: '1:1064467940982:web:cd9b9d3d37953237d04157',
    messagingSenderId: '1064467940982',
    projectId: 'flutter-firebase-auth-4d275',
    authDomain: 'flutter-firebase-auth-4d275.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-4d275.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZN5GkkibKfE1yiIfHjnoDXpaODQk4NYc',
    appId: '1:1064467940982:android:8ab76940d3e2c875d04157',
    messagingSenderId: '1064467940982',
    projectId: 'flutter-firebase-auth-4d275',
    storageBucket: 'flutter-firebase-auth-4d275.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCltYn3LCJYJxAnN2QMjL67njKlEOk-vUM',
    appId: '1:1064467940982:ios:95b986e7c2452a22d04157',
    messagingSenderId: '1064467940982',
    projectId: 'flutter-firebase-auth-4d275',
    storageBucket: 'flutter-firebase-auth-4d275.appspot.com',
    iosBundleId: 'com.repairspots',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCltYn3LCJYJxAnN2QMjL67njKlEOk-vUM',
    appId: '1:1064467940982:ios:95b986e7c2452a22d04157',
    messagingSenderId: '1064467940982',
    projectId: 'flutter-firebase-auth-4d275',
    storageBucket: 'flutter-firebase-auth-4d275.appspot.com',
    iosBundleId: 'com.repairspots',
  );
}
